### ISSUE TITLE
Error in executing Crane

### ISSUE THREAD

**Issue by gioppoluca** [CloudOpting/cloudopting-crane#18]
execure .gencerts

execute compose up and at the end get this:

Compiling /tmp/pip_build_root/Jinja2/jinja2/asyncfilters.py ...
  File "/tmp/pip_build_root/Jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip_build_root/Jinja2/jinja2/asyncsupport.py ...
  File "/tmp/pip_build_root/Jinja2/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

......
  Running setup.py install for cffi
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-AHgTFt-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):

.......
ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-AHgTFt-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cffi
Storing debug log for failure in /root/.pip/pip.log
ERROR: Service 'commander' failed to build: The command '/bin/sh -c pip install -r /usr/src/commander/requirements.txt --force-reinstall --upgrade -I' returned a non-zero code: 1

**Comment by jmcerpa** [comment]
Is it an error in the building phase?
Ubuntu y python can remove some versions of packages. I recommend using the dockerhub container image. This way there are no problems of package versions and there can be no building errors.
